spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookedone
    username: postgres
    password: 3019
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
